transforms:
  corner_link:
    x: 0.24041527012
    y: 0.14635
    z: 0.017975
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
    frame_id: base_link
    child_frame_id: corner_link
  camera_usb_front:
    x: 0.004559324
    y: -0.14635
    z: -0.030175
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
    frame_id: corner_link
    child_frame_id: camera_usb_front
  camera_usb_bottom:
    x: -0.37041527
    y: -0.14635
    z: -0.183143039
    roll: 0.0
    pitch: 1.5707963267948966
    yaw: 0.0
    frame_id: corner_link
    child_frame_id: camera_usb_bottom
  sonar_ping_360:
    x: -0.02041527
    y: -0.14635
    z: -0.128477886
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
    frame_id: corner_link
    child_frame_id: sonar_ping_360
  imu:
    x: -0.238648756
    y: -0.179527925
    z: 0.040239867
    roll: 0.0
    pitch: 0.0
    yaw: 3.141592653589793
    frame_id: corner_link
    child_frame_id: imu
  dvl:
    x: -0.24041527
    y: -0.14635
    z: -0.200875
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
    frame_id: corner_link
    child_frame_id: dvl
  pressure_sensor:
    x: -0.412039805
    y: -0.241660889
    z: 0.061675
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
    frame_id: corner_link
    child_frame_id: pressure_sensor
  gyro:
    x: -0.31751127
    y: -0.2233
    z: 0.048511603
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
    frame_id: corner_link
    child_frame_id: gyro
