transforms:
  corner_link_transform:
    x: 0.219075
    y: -0.3095625
    z: 0.19764375
    roll: 0
    pitch: 0
    yaw: 0
    frame_id: 'base_link'
    child_frame: 'corner_link'
  dvl_link_transform:
    x: -0.20955
    y: 0.0809625
    z: -0.276225
    roll: 0
    pitch: 0
    yaw: 0
    frame_id: 'corner_link'
    child_frame: 'dvl_link'
  imu_link_transform:
    x: -0.219075
    y: 0.3095625
    z: -0.11241875
    roll: 0
    pitch: 0
    yaw: 0
    frame_id: 'corner_link'
    child_frame: 'imu_link'
  sonar_link_transform:
    x: 0.067
    y: 0.31
    z: 0.05
    roll: 0
    pitch: 0
    yaw: 0
    frame_id: 'corner_link'
    child_frame: 'sonar_link'
  cameras_link_transform:
    x: 0
    y: 0.0362
    z: 0
    roll: 0
    pitch: 0
    yaw: 0
    frame_id: 'corner_link'
    child_frame: 'cameras_link'
