services:
  robosub-ros2:
    extends:
      file: docker-compose.yml
      service: robosub-ros2
    build:
      args:
        GIT_USER_NAME: ${GIT_USER_NAME}
        GIT_USER_EMAIL: ${GIT_USER_EMAIL}
        GITHUB_AUTH_SSH_KEY: ${GITHUB_AUTH_SSH_KEY}
        GITHUB_AUTH_SSH_KEY_PUB: ${GITHUB_AUTH_SSH_KEY_PUB}
        GITHUB_SIGNING_SSH_KEY: ${GITHUB_SIGNING_SSH_KEY}
        GIT_ALLOWED_SIGNERS: ${GIT_ALLOWED_SIGNERS}
