services:
  robosub-ros2:
    image: robosub-ros2
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        NO_GIT: ${NO_GIT}
    container_name: onboard2
    tty: true
    privileged: true
    volumes:
      - type: bind
        source: .
        target: /root/dev/robosub-ros2
      - type: bind
        source: /dev
        target: /dev
    ports:
      - 2202:2202
