services:
  robosub-ros2:
    image: robosub-ros2:latest
    container_name: onboard2
    tty: true
    volumes:
      - ./:/root/dev/robosub-ros2
      - ~/.foxglove-studio/:/root/.foxglove-studio
    ports:
      - 28765:28765
