services:
  robosub-ros2:
    image: robosub-ros2
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        NO_GIT: ${NO_GIT}
        AUTHORIZED_SSH_KEY: ${AUTHORIZED_SSH_KEY}
    container_name: onboard2
    tty: true
    volumes:
      - ./:/root/dev/robosub-ros2
    ports:
      - 2202:2202
