services:
  robosub-ros2:
    image: robosub-ros2:latest
    container_name: onboard2
    user: ubuntu
    tty: true
    volumes:
      - ./:/home/ubuntu/robosub-ros2
      - ~/.foxglove-studio/:/home/ubuntu/.foxglove-studio
    ports:
      - 28765:28765
    environment:
      - ROBOT_NAME=${ROBOT_NAME}
