services:
  robosub-ros2:
    image: robosub-ros2:latest
    container_name: onboard2
    tty: true
    network_mode: host
    volumes:
      - ./:/root/dev/robosub-ros2
    ports:
      - 28765:28765
