services:
  robosub-ros2:
    image: robosub-ros2
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        GIT_USER_NAME: ${GIT_USER_NAME}
        GIT_USER_EMAIL: ${GIT_USER_EMAIL}
        GITHUB_AUTH_SSH_KEY: ${GITHUB_AUTH_SSH_KEY}
        GITHUB_AUTH_SSH_KEY_PUB: ${GITHUB_AUTH_SSH_KEY_PUB}
        GITHUB_SIGNING_SSH_KEY: ${GITHUB_SIGNING_SSH_KEY}
        GIT_ALLOWED_SIGNERS: ${GIT_ALLOWED_SIGNERS}
        NO_GIT: ${NO_GIT}
    container_name: onboard2
    tty: true
    volumes:
      - ./:/root/dev/robosub-ros2
    ports:
      - 2202:2202
