services:
  robosub-ros2:
    image: robosub-ros2:latest
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        NO_GIT: ${NO_GIT}
    container_name: onboard2
    tty: true
    volumes:
      - ./:/root/dev/robosub-ros2
    ports:
      - 8765:8765
