services:
  robosub-ros2:
    image: robosub-ros2
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        GIT_USER_NAME: ${GIT_USER_NAME}
        GIT_USER_EMAIL: ${GIT_USER_EMAIL}
    container_name: onboard2
    tty: true
    volumes:
      - ./:/root/dev/robosub-ros2
    ports:
      - 2202:2202
