services:
  robosub-ros2:
    extends:
      file: docker-compose.yml
      service: robosub-ros2
    image: robosub-ros2:latest
    tty: true
    privileged: true
    volumes:
      - /dev:/dev
