depthai:
  ip_range: 192.168.110.0/24
  devices:
    front:
      mac: 44:A9:2C:3E:1F:05
    bottom:
      mac: 44:A9:2C:30:DC:B0

usb_cameras:
  front:
    device_path: /dev/video_front
    topic: /camera/usb/front/compressed
    focal_length: 2.65
    sensor_size:
      width: 3.054
      height: 1.718
    img_size:
      width: 640
      height: 480

  bottom:
    device_path: /dev/video_bottom
    topic: /camera/usb/bottom/compressed
    focal_length: 2.65
    sensor_size:
      width: 3.054
      height: 1.718
    img_size:
      width: 640
      height: 480