arduino:
  peripheral:
    ftdi: B0005AVT
    fqbn: arduino:avr:nano
    core: arduino:avr
    sketch: sketchbooks/PeripheralArduino
    requires_ros_lib: false
    libraries:
      - servo
  thruster:
    ftdi: 02AB8D8451544E5450202020FF0D334A
    fqbn: arduino:megaavr:nano
    core: arduino:megaavr
    sketch: sketchbooks/ThrusterArduino
    requires_ros_lib: true