arduino:
  peripheral:
    ftdi: B0005AVT
    fqbn: arduino:avr:nano
    core: arduino:avr
    sketch: sketchbooks/PeripheralArduino
    libraries:
    sensors:
      - type: pressure
        tag: P
        topic: /sensors/depth
      - type: voltage
        tag: V
        topic: /sensors/humidity
      - type: temperature
        tag: T
        topic: /sensors/temperature
      - type: humidity
        tag: H
        topic: /sensors/humidity
  thruster:
    ftdi: 02AB8D8451544E5450202020FF0D334A
    fqbn: arduino:megaavr:nano
    core: arduino:megaavr
    sketch: sketchbooks/ThrusterArduino
