arduino:
  peripheral:
    ftdi: B0005AVT
    fqbn: arduino:avr:nano
    core: arduino:avr
    sketch: sketches/PeripheralArduino
    libraries:
      - servo
    sensors:
      - type: voltage
        tag: V
        topic: /sensors/voltage
      - type: pressure
        tag: P
        topic: /sensors/depth
      - type: temperature
        tag: T
        topic: /sensors/temperature
      - type: humidity
        tag: H
        topic: /sensors/humidity
    servos:
      - name: marker dropper
        tag: M
        min_pwm: 1100
        max_pwm: 1900
      - name: torpedoes
        tag: T
        min_pwm: 1100
        max_pwm: 1900
  thruster:
    ftdi: 02AB8D8451544E5450202020FF0D334A
    fqbn: arduino:megaavr:nano
    core: arduino:megaavr
    sketch: sketches/ThrusterArduino
dvl:
  ftdi: D309SFWS
  negate_x_vel: false
  negate_y_vel: false
  negate_z_vel: false
ping1D:
  ftdi: DP05ZD1V