name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  docker-build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run docker-build.sh
        run: |
          ./docker-build.sh

      - name: Run build.sh inside Docker container
        run: |
          docker compose exec robosub-ros2 bash /root/dev/robosub-ros2/.github/workflows/build.sh