name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Run docker-build.sh script
      - name: Run docker-build.sh
        run: |
          ./docker-build.sh

      # Step 3: Run build.sh inside the container
      - name: Run build.sh inside Docker container
        run: |
          docker compose exec robosub-ros2 bash /root/dev/robosub-ros2/.github/workflows/build.sh