name: lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint Codebase
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint Codebase
        uses: super-linter/super-linter@latest
        env:
          VALIDATE_ALL_CODEBASE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          VALIDATE_BASH: true
          VALIDATE_PYTHON_FLAKE8: true
          VALIDATE_CLANG_FORMAT: true